# Generated by Django 4.2.4 on 2023-09-09 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='transaction_id',
        ),
    ]
