# Generated by Django 4.2.4 on 2023-09-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_invoice_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=40),
        ),
    ]
