# Generated by Django 4.2.4 on 2023-09-09 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_address_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='shipping_address',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
