# Generated by Django 4.2.4 on 2023-09-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projecttask_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachments',
            old_name='name',
            new_name='file_name',
        ),
    ]
