# Generated by Django 4.2.4 on 2023-08-31 09:41

import django.core.validators
from django.db import migrations, models
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='static/profile_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), employees.models.validate_image_aspect_ratio]),
        ),
    ]
