# Generated by Django 4.2.4 on 2023-10-14 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employees_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profile_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
