# Generated by Django 4.2.4 on 2023-08-31 17:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subsidiaries', '0002_organizations_logo_subsidiaries_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('phone_no', models.IntegerField(unique=True)),
                ('organization_name', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(null=True, upload_to='static/profile_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsidiaries.subsidiaries')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
