# Generated by Django 4.2.4 on 2023-09-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
