# Generated by Django 4.2.4 on 2023-10-14 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_clients_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='profile_image',
            field=models.ImageField(default='static/profile_images/default.png', null=True, upload_to='profile_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
