# Generated by Django 4.2.4 on 2023-09-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
