# Generated by Django 4.2.4 on 2023-10-01 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_address_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_admin_action', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
