# Generated by Django 4.2.4 on 2023-08-31 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidiaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='logo',
            field=models.ImageField(null=True, upload_to='static/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='subsidiaries',
            name='logo',
            field=models.ImageField(null=True, upload_to='static/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
