# Generated by Django 4.2.4 on 2023-08-31 18:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subsidiaries', '0002_organizations_logo_subsidiaries_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budgets',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField()),
                ('amount', models.FloatField()),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsidiaries.subsidiaries')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
