# Generated by Django 4.2.4 on 2023-10-14 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidiaries', '0004_alter_budgets_subsidiary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='logo',
            field=models.ImageField(null=True, upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='subsidiaries',
            name='logo',
            field=models.ImageField(null=True, upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
